service: picotd
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
    events: 
      - schedule: cron(0 12 * * ? *)

    environment:
      NASA_API_KEY: 
      TWILIO_ACCOUNT_SID: 
      TWILIO_AUTH_TOKEN: 
      TWILIO_PHONE_NUMBER: 
      MY_PHONE_NUMBER: 

